lazy_loading:         # 文档懒加载配置相关
  chunk_size: 4096    # 懒加载的分块大小

models:               # 模型配置相关
  chat_model: qwen3:4b          # 聊天模型
  embedding_model: qwen3-embedding:4b     # 嵌入模型
  rag_summary: qwen3:4b       # 摘要模型
  history_summary: qwen3:4b   # 历史摘要模型，如果没有启用记忆功能，该项不会生效

prompts:          # 提示词相关
  system_prompt: ./prompts/main_prompt.md     # 系统提示词
  rag_summary_prompt: ./prompts/rag_summary_prompt.md   # 摘要提示词
  history_summary_prompt: None        # 历史摘要提示词

vector_store:     # 向量数据库相关
  collection_name: knowledge_base   # 向量数据库名称
  persist_directory: ./knowledge    # 持久化保存目录
  chunk_size: 128       # 文档分块大小
  chunk_overlap: 16     # 文档分块重叠大小
  separators: ["\n\n", "\n", " ", "", "。", "，", ",", ".", "！", "？", "!", "?"]   # 分隔符
  k: 3    # 搜索数量
  data: ./data    # 数据目录
  md5_file: ./data/md5.txt    # md5保存位置
  allowed_types: ["pdf", "csv", "txt"]    # 允许的文件类型

file:     # 工具调用文件相关
  outputs: ./outputs  # 存放模型输出目录
  inputs: ./inputs    # 存放用户输入目录
  chunk_size: 4096    # 懒加载的分块大小

history:  # 短期记忆
  type: InMemoryHistory   # 可选的类型有：None, InMemoryHistory(默认)
  trigger:      # 触发记忆总结的条件
    type: ["tokens", "messages"]    # 可选的类型有：tokens(默认), messages，可以复合条件，如["tokens", "messages"] 但value也必须是复合条件
    value: [4000, 20]     # 触发记忆总结的阈值

Debug: True     # 是否开启调试模式